apiVersion: v1
kind: Service
metadata:
  name: kube-test-service
spec:
  selector:
    app: kube-test
  ports:
    - protocol: TCP
      port: 80  # 외부에서 접근할 포트
      targetPort: 8080  # 컨테이너 내부 포트
  type: LoadBalancer